packaging_format = 2

id = "gopodder"
name = "goPodder"

description.en = "Podcast synchronization server compatible with the gPodder API"
description.fr = "Serveur de synchronisation de podcast compatible avec l'API gPodder"

version = "1.4.0~ynh1"

maintainers = []

[upstream]
license = "Apache-2.0"
code = "https://github.com/cbrgm/gopodder"

[integration]
yunohost = '>= 12.1.40'
helpers_version = "2.1"
architectures = ["amd64", "arm64", "i386"]
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"
    
    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        in_subdir = false
        extract = false
        rename = "gopodder"

        amd64.url = "https://github.com/cbrgm/gopodder/releases/download/v1.4.0/gopodder_linux-amd64"
        amd64.sha256 = "6679f8f1ab8848356da9775f614747599af8a339d125dc19a76f035460376264"
        arm64.url = "https://github.com/cbrgm/gopodder/releases/download/v1.4.0/gopodder_linux-arm64"
        arm64.sha256 = "af88a50c3cdd7e5c8e2f847fa2b3775b152f1a0422d6f660f7b974d1529eff13"
        i386.url = "https://github.com/cbrgm/gopodder/releases/download/v1.4.0/gopodder_linux-386"
        i386.sha256 = "df6b1605045dbe313a90a0065757c7ec760209be5b0d6fb95a78e6184f6a4f9e"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.amd64 = "^gopodder_linux-amd64$"
        autoupdate.asset.arm64 = "^gopodder_linux-arm64$"
        autoupdate.asset.i386 = "^gopodder_linux-386$"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    main.show_tile = true
    main.auth_header = false

    [resources.ports]
    main.default = 18080
    main.exposed = false
