packaging_format = 2

id = "gopodder"
name = "goPodder"

description.en = "Podcast synchronization server compatible with the gPodder API"
description.fr = "Serveur de synchronisation de podcast compatible avec l'API gPodder"

version = "1.3.0~ynh1"

maintainers = []

[upstream]
license = "Apache-2.0"
code = "https://github.com/cbrgm/gopodder"

[integration]
yunohost = '>= 12.1.40'
helpers_version = "2.1"
architectures = ["amd64", "arm64", "i386"]
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"
    
    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        in_subdir = false
        extract = false
        rename = "gopodder"

        amd64.url = "https://github.com/cbrgm/gopodder/releases/download/v1.3.0/gopodder_linux-amd64"
        amd64.sha256 = "7f509f31a70e8dbefba537ee683c8c84364c1e4688ba14f2cd8ebc53e0151622"
        arm64.url = "https://github.com/cbrgm/gopodder/releases/download/v1.3.0/gopodder_linux-arm64"
        arm64.sha256 = "55b839e6f9816d372615d65b56eddce8abd9c909b8ddd54df712e04a821136d7"
        i386.url = "https://github.com/cbrgm/gopodder/releases/download/v1.3.0/gopodder_linux-386"
        i386.sha256 = "7bb2888fe189478d9b98c03576259703d5d0b6bad70ca380aa4fcb398e410a57"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.amd64 = "^gopodder_linux-amd64$"
        autoupdate.asset.arm64 = "^gopodder_linux-arm64$"
        autoupdate.asset.i386 = "^gopodder_linux-386$"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    main.show_tile = true
    main.auth_header = false

    [resources.ports]
    main.default = 18080
    main.exposed = false
