#!/bin/bash
### App file generated with YoloGen, the Yunohost app generator, version .

source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

chmod +x "$install_dir/gopodder"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_app_setting_set --key=protect_against_basic_auth_spoofing --value=false

yunohost app ssowatconf

ynh_systemctl --service=nginx --action=reload

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add $app --description="Podcast synchronization server" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action=start

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
