#!/bin/bash
### App file generated with YoloGen, the YunoHost app generator, version .

source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "$install_dir"

chmod +x "$install_dir/gopodder"

ynh_restore "$data_dir"

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore "/etc/systemd/system/$app.service"
systemctl enable $app.service --quiet

yunohost service add $app --description="goPodder"

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

ynh_systemctl --service="$app" --action=start

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"